---
- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.package:
    name: ca-certificates, curl, gnupg
    state: present

# so far, all builds are for 'bionic' only, but it works in other newer distributions as well

- name: 'Add Chromium Team GPG key for bionic'
  ansible.builtin.get_url:
    url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xEA6E302DC78CC4B087CFC3570EBEA9B02842F111'
    dest: /etc/apt/trusted.gpg.d/chromium-team-beta-keyring.asc
    mode: '0644'

- name: 'Set up the Chromium Team repository for bionic'
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/chromium-team-beta-keyring.asc] https://ppa.launchpadcontent.net/chromium-team/beta/ubuntu bionic main'
    state: present
    filename: chromium-beta
    update_cache: true

- name: 'Copy the apt preferences file'
  ansible.builtin.copy:
    src: pin-chromium-team-beta.pref
    dest: '/etc/apt/preferences.d/pin-chromium-team-beta.pref'
    owner: 'root'
    group: 'root'
    mode: '0644'
