---
- name: Add Chromium team PPA
  apt_repository:
    repo: 'ppa:chromium-team/beta'
    codename: 'bionic'
    state: present
    update_cache: true

- name: Copy PPA file
  copy:
    src: pin-chromium-team-beta
    dest: /etc/apt/preferences.d/
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Install Chromium
  apt:
    name: chromium-browser
    state: present
