---
- name: Import platform specific Firefox tasks
  include_tasks: "chromium-ubuntu.yml"
  when: ansible_distribution == 'Pop!_OS' or ansible_distribution == 'Ubuntu'

- name: Install Chromium
  ansible.builtin.package:
    name: chromium-browser
    state: present
