---
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: '*'
    state: latest  # noqa package-latest

- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: true
