---
- name: Checking if snap is installed
  ansible.builtin.stat:
    path: /usr/bin/snap
  register: snap_installed

- name: Unmount the snap mount points
  mount:
    path: /var/snap
    state: unmounted
  when: snap_installed.stat.exists

- name: Uninstall snapd package
  ansible.builtin.apt:
    name: snapd
    state: absent
    purge: true

- name: Block Snap from being reinstalled
  ansible.builtin.copy:
    src: nosnap.pref
    dest: '/etc/apt/preferences.d/nosnap.pref'
    owner: 'root'
    group: 'root'
    mode: '0644'
