---
- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.package:
    name: ca-certificates, curl, gnupg
    state: present

- name: 'Add KeePassXC GPG key'
  ansible.builtin.get_url:
    url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD89C66D0E31FEA2874EBD20561922AB60068FCD6'
    dest: /etc/apt/trusted.gpg.d/keepassxc-keyring.asc
    mode: '0644'

- name: 'Set up the KeePassXC repository'
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/keepassxc-keyring.asc] https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu {{ ansible_distribution_release }} main'
    state: present
    filename: keepassxc
    update_cache: true
