---
- name: 'Enable the free RPM Fusion repository for version {{ ansible_distribution_version }}'
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes


- name: 'Enable the non-free RPM Fusion repository for version {{ ansible_distribution_version }}'
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes

- name: Install fedora-workstation-repositories
  package:
    name:
      - fedora-workstation-repositories
