---
- name: Import platform specific Firefox tasks
  include_tasks: "firefox-ubuntu.yml"
  when: ansible_distribution == 'Pop!_OS' or ansible_distribution == 'Ubuntu'

- name: Install Firefox
  ansible.builtin.package:
    name: firefox
    state: present
