---
- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.package:
    name: ca-certificates, curl, gnupg
    state: present

- name: 'Add Mozilla Team GPG key for {{ distribution }}'
  ansible.builtin.get_url:
    url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0AB215679C571D1C8325275B9BDB3D89CE49EC21'
    dest: /etc/apt/trusted.gpg.d/mozilla-team-keyring.asc
    mode: '0644'

- name: 'Set up the Mozilla Team repository for {{ distribution }}'
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/mozilla-team-keyring.asc] https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu {{ distribution }} main'
    state: present
    filename: firefox
    update_cache: true

- name: 'Copy the apt preferences file'
  ansible.builtin.copy:
    src: pin-firefox-team.pref
    dest: '/etc/apt/preferences.d/pin-firefox-team.pref'
    owner: 'root'
    group: 'root'
    mode: '0644'
