---
- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.package:
    name: ca-certificates, curl, gnupg
    state: present

- name: Install the apt GPG key
  ansible.builtin.get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /etc/apt/trusted.gpg.d/sublime-text-keyring.asc
    mode: '0644'

- name: Add Sublime stable PPA
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/sublime-text-keyring.asc] https://download.sublimetext.com/ apt/stable/
    state: present
    filename: sublime-text
    update_cache: true
