---
- name: Uninstall packages
  ansible.builtin.package:
    name: "{{ uninstall_packages if uninstall_packages is iterable else [] }}"
    state: absent

- name: Install packages
  ansible.builtin.package:
    name: "{{ install_packages if install_packages is iterable else [] }}"
    state: present

- include_tasks: "tasks-{{ ansible_os_family }}.yml"
