---
- name: Install the Flatpak package
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Add the Flathub Flatpak repository remote to the system installation
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present

# remove filters. e.g. fedora-flathub-filter
- name: Remove flathub filters (if any)
  ansible.builtin.command: flatpak remote-modify --system --no-filter flathub

- name: Update after removing filters
  ansible.builtin.command: flatpak update --appstream flathub

- name: Install Flatpak applications
  community.general.flatpak:
    name: '{{ item }}'
    state: present
    method: system
    remote: flathub
  loop: '{{ flatpak_apps }}'
