---
- name: Install the Flatpak package
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Import platform-specific tasks
  include_tasks: "tasks-{{ ansible_os_family }}.yml"

- name: Install Flatpak applications
  community.general.flatpak:
    name: '{{ flatpak_apps if flatpak_apps is iterable else [] }}'
    state: present
    method: system
    remote: flathub
