---
- name: Install the Flatpak package
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Add the Flathub Flatpak repository remote to the system installation
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present

- name: Install Flatpak applications
  community.general.flatpak:
    name: '{{ item }}'
    state: present
    method: system
    remote: flathub
  loop: '{{ flatpak_apps }}'
