---
- name: Set os distribution for Ubuntu systems
  set_fact:
    docker_os: ubuntu
  when: ansible_distribution == 'Pop!_OS' or ansible_distribution == 'Ubuntu'

- name: Set os distribution for Debian systems
  set_fact:
    docker_os: debian
  when: ansible_distribution == 'Debian'

- name: Set os distribution for Fedora systems
  set_fact:
    docker_os: fedora
  when: ansible_distribution == 'Fedora'

- name: Import platform specific Docker tasks
  include_tasks: "tasks-{{ ansible_os_family }}.yml"

- name: Install Docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable and start Docker service
  service:
    name: docker
    enabled: true
    state: started

- name: Ensure group 'docker' exists
  group:
    name: docker
    state: present

- name: Add the current user to group 'docker'
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true
