---
- name: Gather variables
  ansible.builtin.include_vars: 'main.yml'

- name: Import platform specific Docker tasks
  include_tasks: "tasks-{{ ansible_os_family }}.yml"

- name: Install Docker packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable and start Docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Ensure group 'docker' exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the current user to group 'docker'
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true
