---
- name: Install packages to allow apt to use a repository over HTTPS
  ansible.builtin.package:
    name: ca-certificates, curl, gnupg, lsb-release
    state: present

- name: 'Add Docker official GPG key for {{ docker_os }}'
  ansible.builtin.get_url:
    url: 'https://download.docker.com/linux/{{ docker_os }}/gpg'
    dest: /etc/apt/trusted.gpg.d/docker-archive-keyring.asc
    mode: '0644'

- name: 'Set up the stable repository for {{ docker_architecture }} and {{ ansible_distribution_release }}'
  ansible.builtin.apt_repository:
    repo: 'deb [arch={{ docker_architecture }} signed-by=/etc/apt/trusted.gpg.d/docker-archive-keyring.asc] https://download.docker.com/linux/{{ docker_os }} {{ ansible_distribution_release }} stable'
    state: present
    filename: docker
    update_cache: true
