---
- name: Install required packages
  ansible.builtin.package:
    name: dnf-plugins-core
    state: present

- name: 'Import {{ docker_os }} RPM Repo'
  ansible.builtin.get_url:
    url: 'https://download.docker.com/linux/{{ docker_os }}/docker-ce.repo'
    dest: /etc/yum.repos.d/docker-ce.repo
