---
- name: Register architecture variable
  ansible.builtin.shell: dpkg --print-architecture
  register: docker_architecture
  ignore_errors: true

- name: Install packages to allow apt to use a repository over HTTPS
  package:
    name: ca-certificates, curl, gnupg, lsb-release
    state: present

- name: 'Add Docker official GPG key for {{ docker_os }}'
  apt_key:
    url: 'https://download.docker.com/linux/{{ docker_os }}/gpg'
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: 'Set up the stable repository for {{ docker_architecture.stdout }} and {{ ansible_distribution_release }}'
  apt_repository:
    repo: 'deb [arch={{ docker_architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ docker_os }} {{ ansible_distribution_release }} stable'
    state: present
    update_cache: true
