---
- name: Copy Docker configuration file
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/files/docker-config/daemon.json'
    dest: '/etc/docker/daemon.json'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
    - restart docker
