---
- name: Copy Docker configuration file
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/files/docker-config/daemon.json'
    dest: '/etc/docker/daemon.json'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: Restart service docker
  ansible.builtin.service:
    name: docker
    state: restarted
